CREATE TABLE account(personid INT, accountid INT, balance INT, PRIMARY KEY(accountid));

INSERT INTO account VALUES(1,1,10);
INSERT INTO account VALUES(1,2,20);
INSERT INTO account VALUES(1,3,15);
INSERT INTO account VALUES(2,4,19);
INSERT INTO account VALUES(2,5,15);
INSERT INTO account VALUES(3,6,5);
INSERT INTO account VALUES(3,7,19);
INSERT INTO account VALUES(3,8,23);
INSERT INTO account VALUES(3,9,96);
INSERT INTO account VALUES(4,10,15);


